# -*- coding: utf-8 -*-
""" AI-Driven Automated Interviewer for Project Presentations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeL33UaOx7qmj7u2HwpHyD3ozahpYQSO
"""

!pip -q install easyocr faster-whisper transformers sentencepiece accelerate keybert sentence-transformers gradio pillow opencv-python-headless

# Cell 2 — Imports and model loading

import re
import json
from pathlib import Path

import numpy as np
from PIL import Image

import easyocr
from faster_whisper import WhisperModel
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from keybert import KeyBERT
from sentence_transformers import SentenceTransformer, util

# OCR
ocr_reader = easyocr.Reader(["en"], gpu=False)

# Speech-to-text
stt_model = WhisperModel(
    "small",
    device="cpu",
    compute_type="int8"
)

# FLAN-T5 Question Generator 
model_name = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def run_flan(prompt, max_new_tokens=160):
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Keywords
kw_model = KeyBERT(model="all-MiniLM-L6-v2")

# Embeddings
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Cell 3 — Helper functions 

def clean_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    return text

def extract_text_from_image(image_path: str) -> str:
    results = ocr_reader.readtext(image_path, detail=0)
    return clean_text(" ".join(results))

def transcribe_audio(audio_path: str) -> str:
    segments, info = stt_model.transcribe(
        audio_path,
        beam_size=5
    )

    parts = [seg.text for seg in segments]
    return clean_text(" ".join(parts))

def extract_keywords(text: str, top_n: int = 8):
    if len(text.split()) < 5:
        return []

    kws = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 3),
        stop_words="english",
        top_n=top_n
    )

    return [k for k, _ in kws]

def similarity(a: str, b: str) -> float:
    if not a.strip() or not b.strip():
        return 0.0

    va = embedder.encode(a, convert_to_tensor=True)
    vb = embedder.encode(b, convert_to_tensor=True)

    return float(util.cos_sim(va, vb)[0][0])

# Question generation
def generate_questions(context: str, n: int = 5):

    prompt = f"""
Generate exactly {n} concise interview questions from this project context.

Focus on:
- architecture
- implementation
- model choice
- evaluation
- originality
- limitations

Return only questions.
One question per line.

Context:
{context[:3000]}
"""

    raw = run_flan(prompt)

    lines = [
        re.sub(r"^\d+[\).\s-]*", "", x).strip()
        for x in raw.split("\n")
    ]

    questions = [
        x for x in lines
        if len(x) > 10
    ]

    fallback = [
        "Can you explain the architecture of your project?",
        "What problem does your project solve?",
        "Why did you choose these models or libraries?",
        "What implementation challenges did you face?",
        "How did you evaluate your system?",
        "What are the limitations of your solution?",
        "How can the project be improved further?",
        "Which part of the project is most original?"
    ]

    for q in fallback:
        if len(questions) >= n:
            break

        if q not in questions:
            questions.append(q)

    return questions[:n]

# Adaptive follow-up
def generate_followup(question: str, answer: str, context: str):

    prompt = f"""
Question:
{question}

Student answer:
{answer}

Project context:
{context[:1000]}

Generate 1 short follow-up interview question
to probe deeper into technical understanding.

Return only the question.
"""

    raw = run_flan(prompt)

    return raw.strip()

# Scoring
def score_answer(answer: str, context: str, question: str):

    answer_l = answer.lower()

    kws = extract_keywords(context, top_n=8)

    keyword_coverage = (
        sum(1 for kw in kws if kw.lower() in answer_l)
        / max(len(kws), 1)
    )

    sim_context = similarity(answer, context)
    sim_question = similarity(answer, question)

    technical_depth = round(
        min(
            100,
            35 * sim_context +
            35 * keyword_coverage * 100 +
            30 * sim_question
        ),
        2
    )

    clarity = round(
        min(
            100,
            20 + min(len(answer.split()) / 1.2, 80)
        ),
        2
    )

    originality = round(
        max(0, 100 - 80 * sim_context),
        2
    )

    implementation = round(
        min(
            100,
            40 * keyword_coverage * 100 +
            30 * sim_question +
            30 * min(len(answer.split()) / 40, 1) * 100
        ),
        2
    )

    overall = round(
        0.35 * technical_depth +
        0.20 * clarity +
        0.15 * originality +
        0.30 * implementation,
        2
    )

    if overall >= 80:
        feedback = (
            "Very strong answer with good technical depth."
        )

    elif overall >= 60:
        feedback = (
            "Good answer but needs more implementation details."
        )

    else:
        feedback = (
            "Weak answer. Add clearer technical explanation."
        )

    return {
        "technical_depth": technical_depth,
        "clarity": clarity,
        "originality": originality,
        "implementation_understanding": implementation,
        "overall": overall,
        "feedback": feedback
    }

# Cell 4 — Input files

# Replace these with your actual files in Colab
image_path = "/content/Image.png"   
audio_path = "/content/u_t60o3simia-hanuman-song-maker-song-abhi-404570.mp3"    

assert Path(image_path).exists(), f"Image not found: {image_path}"
assert Path(audio_path).exists(), f"Audio not found: {audio_path}"

print("Files found successfully.")

# Cell 5 — Extract OCR and transcript

ocr_text = extract_text_from_image(image_path)
stt_text = transcribe_audio(audio_path)

project_context = clean_text(ocr_text + " " + stt_text)

print("OCR TEXT:\n", ocr_text[:1200])
print("\nSTT TEXT:\n", stt_text[:1200])
print("\nMERGED CONTEXT LENGTH:", len(project_context))

# Cell 6 — Generate interview questions

questions = generate_questions(project_context, n=5)

print("Generated Questions:\n")
for i, q in enumerate(questions, 1):
    print(f"{i}. {q}")

# Cell 7 — Interactive interview loop with adaptive follow-up

results = []
question_history = []

for i, q in enumerate(questions, 1):

    print(f"\nQ{i}: {q}")

    answer = input("Your answer: ").strip()

    result = score_answer(
        answer,
        project_context,
        q
    )

    # Adaptive follow-up condition
    if result["overall"] < 70 or len(answer.split()) < 25:

        followup = generate_followup(
            q,
            answer,
            project_context
        )

        print("\nFollow-up Question:")
        print(followup)

        followup_answer = input(
            "Your follow-up answer: "
        ).strip()

        result["followup_question"] = followup
        result["followup_answer"] = followup_answer

    else:

        result["followup_question"] = ""
        result["followup_answer"] = ""

    result["question"] = q
    result["answer"] = answer

    results.append(result)
    question_history.append(q)

print("\nInterview completed successfully.")

# Cell 8 — Print score summary

import pandas as pd

df = pd.DataFrame(results)[[
    "question",
    "overall",
    "technical_depth",
    "clarity",
    "originality",
    "implementation_understanding",
    "feedback"
]]

display(df)

print("\nAverage Score:", round(df["overall"].mean(), 2))

# Cell 9 — Generate PDF report

!pip -q install reportlab
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def generate_report(results, student="Student", project="AI-Driven Automated Interviewer"):
    doc = SimpleDocTemplate("interview_report.pdf", pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(project, styles["Title"]))
    story.append(Paragraph(f"Student: {student}", styles["Normal"]))
    story.append(Spacer(1, 12))

    avg_score = sum(r["overall"] for r in results) / max(len(results), 1)
    story.append(Paragraph(f"Overall Score: {avg_score:.2f}/100", styles["Heading2"]))
    story.append(Spacer(1, 10))

    summary_data = [["Metric", "Average"]]
    for key in ["technical_depth", "clarity", "originality", "implementation_understanding"]:
        avg_val = sum(r[key] for r in results) / max(len(results), 1)
        summary_data.append([key.replace("_", " ").title(), f"{avg_val:.2f}"])

    table = Table(summary_data, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    story.append(Spacer(1, 14))

    for idx, r in enumerate(results, 1):
        story.append(Paragraph(f"Q{idx}: {r['question']}", styles["Heading3"]))
        story.append(Paragraph(f"Answer: {r['answer']}", styles["Normal"]))

        if r.get("followup_question"):
            story.append(Paragraph(f"Follow-up: {r['followup_question']}", styles["Normal"]))
            story.append(Paragraph(f"Follow-up Answer: {r['followup_answer']}", styles["Normal"]))

        story.append(Paragraph(f"Score: {r['overall']}/100", styles["Normal"]))
        story.append(Paragraph(f"Feedback: {r['feedback']}", styles["Normal"]))
        story.append(Spacer(1, 10))

    doc.build(story)
    print("PDF saved: interview_report.pdf")

generate_report(results, student="Rahul Kumar Sharma")

